/**
  * @file mainwindow.cpp
  * @author Andrew Hoover
  * @date 9/20/2016
  * @brief Create the main window and handle toolbar input.
  *
  * Implementation of MainWindow class. Sets up and deletes the application
  * window that holds the OpenGL widget and toolbar, and has functions
  * to handles when the toolbar options are pressed.
  */

#include "mainwindow.h"
#include "ui_mainwindow.h"
#include "globals.h"
#include <QInputDialog>

/**
 * Constructor to create the main window.
 * Auto generated by Qt.
 *
 * @brief MainWindow::MainWindow
 * @param parent
 */

MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{
    ui->setupUi(this);
}

/**
 * Deconstructor to clean up the application.
 * Auto generated by Qt.
 *
 * @brief MainWindow::~MainWindow
 */

MainWindow::~MainWindow()
{
    delete ui;
}

/**
 * Exit button function. Close the application.
 * Auto generated by Qt Designer.
 *
 * @brief MainWindow::on_action_Exit_triggered
 */

void MainWindow::on_action_Exit_triggered()
{
    this->close();
}

/**
 * Restart button fuction. Flag the global variable RESTART to
 * true so the GlWidget function paintGL can delete and create a
 * new instance of Gravity.
 *
 * @brief MainWindow::on_actionRestart_triggered
 */

void MainWindow::on_actionRestart_triggered()
{
    RESTART = true;
}

/**
 * Gravity button function. Allow the user to enter a number
 * between 0 and 1 for a new strength of gravity, and update
 * the GRAVITY global variable to hold the new value.
 *
 * @brief MainWindow::on_action_Gravity_triggered
 */

void MainWindow::on_action_Gravity_triggered()
{
    bool ok;
    GRAVITY_FORCE = QInputDialog::getDouble(this, tr("Gravity"),
                                          tr("Strength of gravity:"),
                                          GRAVITY_FORCE, 0, 1, 2, &ok);
}

/**
 * Pause button function. Flip the global CONTINUE variable, so
 * the GlWidget funtion paintGL will no longer call the Gravity
 * function to update the universe.
 *
 * @brief MainWindow::on_action_Pause_triggered
 */

void MainWindow::on_action_Pause_triggered()
{
    CONTINUE = !CONTINUE;
}

/**
 * Preset 1 button function. Set the PRESET value to 1, and restart
 * the universe.
 *
 * @brief MainWindow::on_action1_triggered
 */

void MainWindow::on_action1_triggered()
{
    PRESET = 1;
    RESTART = true;
}

/**
 * Preset 2 button function. Set the PRESET value to 2, and restart
 * the universe.
 *
 * @brief MainWindow::on_action2_triggered
 */

void MainWindow::on_action2_triggered()
{
    PRESET = 2;
    RESTART = true;
}
